services:
  db:
    image: postgres:15
    container_name: postgres_etl
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: etl_app
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "db:5432", "--timeout=30", "--strict", "--"]
    command: ["python", "main.py"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: myuser
      DB_PASSWORD: mypassword
    volumes:
      - .:/app
    restart: "no"

volumes:
  postgres_data:
